### ISSUE TITLE
Add "My QTH" button

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#1]
add this button so that the user can change the map center back to his QTH

**Comment by 4Z1KD** [comment]
clicking on the map changes its center that point so we need a way to quickly allow the users to change the view back to their QTH

**Comment by wantyapps** [comment]
Idea: after the user enters a grid into the text box below the map, a button would appear with the option to save the grid as a QTH.
This grid will be saved in the browser's local storage, and can be accessed later. Not supposed to be that hard of an implementation.
Future: When userspace is implemented, each user can have their QTH saved on the server, and have multiple QTH's under multiple names.
i.e.
"Home": "KM72kb"
"Work": "JE1ks"
etc. etc.

**Comment by doctoromer** [comment]
Implemented as default locator saved in a settings window. Click on "My QTH" resets the map to the user's home locator and not to the center of the map, which is JJ00AA.
