### ISSUE TITLE
UI finishes

### ISSUE THREAD

**Issue by doctoromer** [4Z1KD/HolyCluster#112]
We would like to add:
* Title of "Holy Cluster" in the upper filters bar
* The icon in the top left corner
* "i" button in the bottom left corner that will open "About" modal window.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added 'Holy Cluster' title to the upper filters bar, included the icon in the top left corner, and added an 'i' button in the bottom left corner that opens an 'About' modal window.

You can review changes in this commit: https://github.com/lkilu6456546/4Z1KD-HolyCluster-112/commit/0764ee9866f52c175c06561764eb9cfb77436dc4.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
