### ISSUE TITLE
לסדר שהתראה תוצג במידה ותחנה שמוגדרת להתראה מופיע בקלסטר גם אם היא בבנד שמסומן לא להצגה.

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#115]
לא נרצה לפספס קשר עם תחנה שאנחנו מחכים לה והיא במקרה בבנד שסימנו לא להציג.

**Comment by doctoromer** [comment]
I have added a count of alerted spots that are not displayed in each band
