### ISSUE TITLE
Enhance the Spot filter

### ISSUE THREAD

**Issue by 4Z1KD** [4Z1KD/HolyCluster#16]
Lets make a smart filter that can filter stations like /P /M /MM etc'
Also, we may want to filter by a substring of a CALLSIGN

**Comment by 4Z1KD** [comment]
1. Add a new icon for filtering (next to the highlight icon?)
2. create two lists for Blacklist and Whitelist

**Comment by doctoromer** [comment]
The only this left to implement is #79.
