### ISSUE TITLE
Map Radius

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#18]
The map radius shall be modified by the user (this is like zoom ability). 
The minimum radius can be 1000 Km and the maximum should be 20,000 KM. I think that 20,000 Km is a must.
At map radius of 20,000 Km the user will she the whole reported station.
Dani

**Comment by eladkeidan** [comment]
this seems like a duplicate of issue #6 (zoom ability), what's the difference? you mean a dialog box with the radius to set the zoom level?

**Comment by dankatzman** [comment]
המפה צריכה להגיע לרדיוס 20000
נכון להיום היא לא מגיע לרדיוס כזה אלא מציגה תמונה שהיא מבט על כדור הארץ מהאין סוף

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________
