### ISSUE TITLE
Add azimuth labels around the map 

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#2]

**Comment by 4Z1KD** [comment]
Something like that:


![Image](https://github.com/4Z1KD/HolyCluster/assets/24712835/d28e12e4-4153-4fb7-ac77-a7703590a987)

**Comment by doctoromer** [comment]
I've added azimuth labels so I'm closing this issue:
![image](https://github.com/user-attachments/assets/9110950a-9f7c-48f3-a003-e2b6ff0554db)
