### ISSUE TITLE
Add a textual cluster next to the map

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#4]
show a text list of the current spots we want the show : spotter, dx, time, fr, mode

**Comment by 4Z1KD** [comment]
It should display the list of spots and possibly the ability to group by band/continent/mode

**Comment by doctoromer** [comment]
I've added spots display. Currently, Grouping is only implemented for band, not continent or mode so I'm not closing this issue:
![image](https://github.com/user-attachments/assets/5e9ed204-8a8f-4f5a-b2c0-6d32fcf3dde2)
