### ISSUE TITLE
Add Computer Aided Transceiver (CAT) capabilities

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#5]
The radio will change to the Freq of a spotted station by clicking on the station report in the text frame or on the azimuth map

**Comment by 4Z1KD** [comment]
This package may be helpful:
[omnipyrig](https://pypi.org/project/omnipyrig/)

**Comment by 4Z1KD** [comment]
We have made some progress in this direction.
[omnipyrig](https://pypi.org/project/omnipyrig/) is used in a module named RadioController.
This module is communicating with the main app, namely the web page that hosts the app, using WebSockets.
It defines a very thin DTO to get 'commands' from the client, and uses the python wrapper to leverage omnirig on the hardware side.
Initial integration showed that this is feasible.
Some more effort is required to separate the web server from the library to a more appropriate class.
