### ISSUE TITLE
Report how many QSOs are reported in the current state

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#53]
Report how many stations are reported at the current moment. the report shall be on the area of the text cluster and be updated according to the total number of reports

**Comment by doctoromer** [comment]
This will be easy. We count every spot we have, or only the filtered spots that are actually displayed?

**Comment by doctoromer** [comment]
Also, I think we should put in the the map, we have empty area there, below the radius.

**Comment by dankatzman** [comment]
I think we shall report only how many are displayed

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by doctoromer** [comment]
Ok, so I've implemented it, you can see it at the website.
