### ISSUE TITLE
Issue with highlighting. not visible in the text area

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#63]
There are cases that text about a highlighted arc is not visible. 
In case the text frame of the relevant band contain many stations, it can be that the relevant qso is at the part of the list that is out of the frame.  So the user is highlighting an arc, but do not see the information in the text area. 
I think we shall create a solution for that.

**Comment by doctoromer** [comment]
Now hovering over a spot in the map scrolls the spot into view in the spots table, but this is very annoying.
