### ISSUE TITLE
Give a specific symbol to a mode

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#69]
An idea:
Instead of giving square symbol to ALL dx station no matter what mode they use, we can give specific a symbol. 
For example: all SSB stations on the map will be square, all CW will be triangle, all FT8,4 and digital will be bold +
The control buttons of the text cluster will also have those shapes instead of round corner square as they are now.

**Comment by doctoromer** [comment]
SSB - Square
CW - Triangle
DIGITAL/FT8/FT4 - Plus

**Comment by doctoromer** [comment]
Very cool
