### ISSUE TITLE
לציין את מספר הדיווחים שיש בכל בנד

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#75]
מציע לציין את מספר הדיווחים שיש בכל רגע נתון בתוך הלחצן של הבנד בשורת לחצני הבנדים. זה יכול לעזור למשתמש להחליט באיזה בנד כדאי לו לעבוד.

**Comment by doctoromer** [comment]
We can add the number of spots in each band inside the ONLY/ALL/NONE popup button

**Comment by doctoromer** [comment]
We should add it to the modes and continents, not only the bands.
