### ISSUE TITLE
להקטין את רוחב חלון הטקסטים

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#77]
בחלון הטקסטים עכשיו יש מרווח גדול בין עמודה לעמודה. כדאי לצמצם אותו שמאלה ובכך יש סיכוי שיתפנה שטח מסך חשוב בצד ימין של המסך לכל מיני הגדרות פילטרים שיוכלו להיות ניראות, מה שלא קיים היום.

**Comment by doctoromer** [comment]
I've added a column for continent filtering and the textual table is automatically shrinking.
In the future, when we'll want to add more columns the table will shrink more.
