### ISSUE TITLE
תקלה? כשקשת מסמנת תחנה שמוגדרת בהתראות (קו מרוסק דינמי), התחנה עצמה לא מופיעה מודגשת ברשימה

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#82]

**Comment by doctoromer** [comment]
This is how an alerted spot is displayed:
![image](https://github.com/user-attachments/assets/1623269c-f24c-42f8-b207-8d6c19797916)
The callsign is highlighted with green background. If it's not distinguished enough I can change it.

**Comment by 4Z1KD** [comment]
סוכם שנקיף במסגרת מרוסקת ברוחב 2PX
