### ISSUE TITLE
שינוי צבע רקע של תחום תדר או מוד או יבשת

### ISSUE THREAD

**Issue by dankatzman** [4Z1KD/HolyCluster#99]
אני מציע שהרקע של כל אחד מהכפתורים הנ"ל יהפוך ללבן ויוקף במסגרת שחורה עם פינות מעוגלות בדיוק בגודל של הכפתור. כיום כשהרקע הופך לאפור, לא ממש ברור שזה תחום שלא נבחר. למשל עם לוחצים על ה 40 מטר כדי שלא יוצג, הוא הופך לאפור ונראה רלוונטי בדיוק כמו שר החברים שלו בעמודה.

**Comment by doctoromer** [comment]
I changed it to this:
![image](https://github.com/user-attachments/assets/d8727ac7-7e1e-447f-9511-0b1986c0b8f5)
I'm closing this issue but feel free to reopen it if the style needs further changes.

**Comment by dankatzman** [comment]
נראה לי שזה טוב ככה. יופי

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________
